---
title: "EDA"
author: "Brian Cochran"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries}
library(tidyverse)
library(fpp3)
library(glmnet)
library(ggthemes)
library(patchwork)
library(plyr)
library(sqldf)
library(readxl)
library(glmnet)
library(pls)
library(randomForest)
library(e1071)

theme_set(theme_economist())
```

```{r load_data}
sched2023 <- read.csv("~/MinneMudac-Rstans/data/2023_MLBSchedule.csv")
og_sched <- read.csv("~/MinneMudac-Rstans/data/OriginalSchedulesFixed.csv")
game_logs <- read.csv("~/MinneMudac-Rstans/data/GameLogsFixed.csv")
```

```{r eda-gamelogs}
game_logs <- game_logs %>%
  as_tibble() %>%
  mutate(Date=as.Date(as.character(Date), format="%Y%m%d")) %>%
  mutate(Attendance=Attendance/1000) %>%
  mutate(Rivalry=MinnisodaCompdata2$`Rivalry Game`) %>%
  filter(year(Date)!=2020, Attendance>0)

game_logs %>%
  filter(year(Date)==2001) %>%
  ggplot(aes(x=Date, y=Attendance))+
  geom_point()

str(game_logs)
```



```{r count_streaks}
countStreaks <- function(results){
  streaks <- rep(0, length(results))
  count <- 0
  for (i in 2:length(results)){
    if (results[i-1] == "Win") {
      count = count + 1
    } else if (results[i-1] == "Loss"){
      count = 0
    }
    streaks[i] = streaks[i] + count
  }
  return(streaks)
}
```

```{r get_streaks}
all_logs <- game_logs %>%
  pivot_longer(cols=c("HomeTeam", "VisitingTeam"), names_to="HomeorAway", values_to="Team") %>%
  mutate(Result=ifelse(HomeorAway=="HomeTeam", case_when(
    HomeTeamScore>VistingTeamScore ~ "Win", HomeTeamScore==VistingTeamScore ~ "Tie", HomeTeamScore<VistingTeamScore ~ "Loss"
  ), case_when(HomeTeamScore>VistingTeamScore ~ "Loss", HomeTeamScore==VistingTeamScore ~ "Tie", HomeTeamScore<VistingTeamScore ~ "Win")))

temp_logs <- all_logs[0,]
for (team in unique(game_logs$HomeTeam)){
  temp <- all_logs %>%
    filter(Team==team) %>%
    mutate(WinStreak=countStreaks(Result))
  temp_logs <- rbind(temp_logs, temp)
}

all_logs <- temp_logs %>%
  select(-Result) %>%
  pivot_wider(names_from=HomeorAway, values_from=c(Team, WinStreak))
names(all_logs)[names(all_logs) == 'Team_HomeTeam'] <- 'HomeTeam'
names(all_logs)[names(all_logs) == 'Team_VisitingTeam'] <- 'VisitingTeam'
```

```{r allteams_streaks}
(all_logs %>%
  ggplot(aes(x=Attendance, y=as.factor(WinStreak_HomeTeam)))+
  geom_boxplot()+
    labs(y="Home Team Win Streak", x="Attendance(thousands)")) |
(all_logs %>%
  ggplot(aes(x=WinStreak_HomeTeam, y=Attendance))+
  geom_point()+
  geom_smooth()+
   labs(x="Home Team Win Streak", y="Attendance(thousands)")) |
  plot_annotation(title="Relationship Between Home Team Win Streak and Attendance")
(all_logs %>%
  ggplot(aes(x=Attendance, y=as.factor(WinStreak_VisitingTeam)))+
  geom_boxplot()+
    labs(y="Visiting Team Win Streak", x="Attendance(thousands)")) |
(all_logs %>%
  ggplot(aes(x=WinStreak_VisitingTeam, y=Attendance))+
  geom_point()+
  geom_smooth()+
   labs(x="Visiting Team Win Streak", y="Attendance(thousands)")) |
  plot_annotation(title="Relationship Between Visiting Team Win Streak and Attendance")
```

```{r twins_streaks}
(all_logs %>%
  filter(HomeTeam=="MIN") %>%
  ggplot(aes(x=Attendance, y=as.factor(WinStreak_HomeTeam)))+
  geom_boxplot()+
    labs(y="Home Team Win Streak", x="Attendance(thousands)")) |
(all_logs %>%
  filter(HomeTeam=="MIN") %>%
  ggplot(aes(x=WinStreak_HomeTeam, y=Attendance))+
  geom_point()+
  geom_smooth()+
   labs(x="Home Team Win Streak", y="Attendance(thousands)")) |
  plot_annotation(title="Relationship Between Home Team Win Streak and Attendance")
(all_logs %>%
  filter(HomeTeam=="MIN") %>%
  ggplot(aes(x=Attendance, y=as.factor(WinStreak_VisitingTeam)))+
  geom_boxplot()+
    labs(y="Visiting Team Win Streak", x="Attendance(thousands)")) |
(all_logs %>%
  filter(HomeTeam=="MIN") %>%
  ggplot(aes(x=WinStreak_VisitingTeam, y=Attendance))+
  geom_point()+
  geom_smooth()+
   labs(x="Visiting Team Win Streak", y="Attendance(thousands)")) |
  plot_annotation(title="Relationship Between Visiting Team Win Streak and Attendance")
```

```{r twins_visitingteams}
twins_logs <- game_logs %>%
  filter(HomeTeam=="MIN")

twins_logs %>%
  ggplot(aes(x=Attendance, y=VisitingTeam))+
  geom_boxplot()+
  labs(title="Attendance at Twins Home Games")
```

```{r weather_data}
#Create park codes and attach location identifier via mapvalues function
#The location identifier comes from a string in the weather station name
park_codes <- read.csv("~/MinneMudac-Rstans/data/parkcode.csv") %>%
  select(PARKID, CITY) %>%
  mutate(Loc=CITY)
names(park_codes) <- c("ParkID", "City", "Loc")
park_codes$Loc <- mapvalues(park_codes$Loc,
                            from=c("Collinwood", "Covington", "Dunedin", "Dyersville", "Geauga Lake", "Gloucester City", "Harrison", "Irondequoit", "Lake Buena Vista", "London", "Ludlow", "Maspeth", "Middletown", "Bloomington", "Newburgh Township", "Brooklyn", "Queens", "Providence", "Springfield", "Three Rivers", "Troy", "Warwick", "Watervliet", "Weehawken", "West New York", "New York"),
                            to=c("Cleveland", "Cincinnati", "Tampa", "Dubuque", "Cleveland", "Philadelphia", "Newark", "Rochester", "Orlando", "Heathrow", "Cincinnati", "JFK", "Hartford", "Minneapolis", "Evansville", "JFK", "JFK", "Rhode Island", "Hartford", "Syracuse", "Albany", "Rhode Island", "Albany", "JFK", "JFK", "JFK"))


#Combine two weather datasets into one
weather1 <- read.csv("~/MinneMudac-Rstans/data/weather1.csv")
weather2 <- read.csv("~/MinneMudac-Rstans/data/weather2.csv")
weather <- rbind(weather1, weather2) %>%
  select(DATE, PRCP, NAME) %>%
  mutate(DATE=as.Date(DATE))
names(weather) <- c("Date", "Prcp", "Name")


#Merge weather and park codes datasets to add ParkID column to weather
park_weather <- sqldf("
                      SELECT *
                      FROM weather, park_codes
                      WHERE Name LIKE '%'||Loc||'%'
                      ") %>%
  select(Date, Prcp, ParkID)


#Join park_weather and all_logs by ParkID and Date
all_logs <- merge(all_logs, park_weather, by.x=c("Date", "BallParkID"), by.y=c("Date", "ParkID"), all.x=TRUE)

#Create dummy variable for rain/no rain
all_logs <- all_logs %>%
  mutate(Rain=ifelse(Prcp>1, 1, 0))
```

```{r eda_weather1}
(all_logs %>%
  filter(!is.na(Prcp)) %>%
  ggplot(aes(x=Attendance, fill=as.factor(Rain)))+
  geom_density(alpha=0.5)+
   labs(y="Density", fill="")+
   scale_fill_discrete(labels=c("No Rain", "Rain"))) /
(all_logs %>%
   filter(!is.na(Prcp)) %>%
   mutate(Rain=ifelse(Rain==1, "Rain", "No Rain")) %>%
   ggplot(aes(x=Attendance, y=(Rain)))+
   geom_boxplot()+
   labs(y="")) /
  plot_annotation(title="Distribution of Attendance Based on Weather")
```

```{r eda_weather2}
all_logs %>%
  filter(!is.na(Prcp), Prcp>0, Prcp<7) %>%
  ggplot(aes(x=Prcp, y=Attendance))+
  geom_point()+
  geom_smooth()+
  labs(title="Attendance vs Precipitation", x="Precipitation")
```

```{r eda_general}
all_logs <- all_logs %>%
 mutate(Month=month(Date, label=TRUE))
all_logs$DayofWeek <- factor(all_logs$DayofWeek, levels=c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"))
(all_logs %>%
  ggplot(aes(x=Month, y=Attendance))+
  geom_boxplot()+
  labs(x="", y="Attendance(thousands)")) |
(all_logs %>%
  ggplot(aes(x=DayofWeek, y=Attendance))+
  geom_boxplot()+
  labs(x="", y="Attendance(thousands)")) |
  plot_annotation(title="Attendance During Year/Week")
```

```{r testing_models}
sample <- sample(c(TRUE, FALSE), nrow(all_logs), replace=TRUE, prob=c(0.7,0.3))
train  <- all_logs[sample, ]
test   <- all_logs[!sample, ]


# Linear Regression
lm_model <- lm(Attendance ~ DayofWeek + Month + HomeTeam + VisitingTeam + BallParkID + Rain + WinStreak_HomeTeam + NumberofGames + HomeTeamGameNumber + VisitingTeamGameNumber, data=train)
summary(lm_model)

# Principal Component Regression
# pcr_model <- pcr(Attendance ~ DayofWeek + Month + HomeTeam + VisitingTeam + Rivalry + BallParkID + Rain + WinStreak_HomeTeam, data=all_logs)
# summary(pcr_model)
# validationplot(pcr_model)

# Lasso Regression
# y <- all_logs$Attendance
# x <- data.matrix(all_logs[, c("DayofWeek", "Month", "HomeTeam", "VisitingTeam", "Rivalry")])
# cv_model <- cv.glmnet(x, y, alpha=1)
# lam <- cv_model$lambda.min
# lasso_model <- glmnet(x, y, lambda=lam)
# coef(lasso_model)

# Random Forest
rf_model <- randomForest(Attendance ~ DayofWeek + Month + HomeTeam + VisitingTeam + BallParkID + Rain + WinStreak_HomeTeam + NumberofGames + HomeTeamGameNumber + VisitingTeamGameNumber, ntree=100, data=all_logs, na.action=na.omit)
print(rf_model)

# Naive Bayes
nb_model <- model <- naiveBayes(Attendance ~ DayofWeek + Month + HomeTeam + VisitingTeam + BallParkID + Rain + WinStreak_HomeTeam + NumberofGames + HomeTeamGameNumber + VisitingTeamGameNumber, data = all_logs)
summary(nb_model)
```